server:
  port: 8888

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@127.0.0.1:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Li-Zhiren/spring-boot-cloud
          search-paths: config-repo
  rabbitmq:
    host: 104.243.20.180
    username: shenzhi0222
    password: shenlzr66
    port: 15672

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
