spring:
  application:
    name: zipkin
  rabbitmq:
    host: 104.243.20.180
    username: shenzhi0222
    password: shenlzr66
    port: 15672

server:
  port: 9411

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}
